**4.1 Exercise on Functions:**

Task - 1:
Create a Python program that converts between different units of measurement. • The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume). 2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types. • Requirements:
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values). 3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and return value.
• Conversion Options:
1. Length:
– Convert meters (m) to feet (ft).
– Convert feet (ft) to meters (m).
2. Weight:
– Convert kilograms (kg) to pounds (lbs).
– Convert pounds (lbs) to kilograms (kg).
3. Volume:
– Convert liters (L) to gallons (gal).
– Convert gallons (gal) to liters (L).


In [ ]:
print("Python program that converts between different units of measurement.")
print("Press  1  for length \n Press 2 for weight \n Press 3 for VOlume")


def meters_to_feet():
  print("Convert meters (m) to feet (ft) : ")
  y = float(input("Input meters (m) : "))
  x = y * 3.28084;
  print("Converted Value from meeter to feet " + str(x) + "ft")

def feet_to_meters():
  print("Convert feet (ft) to meters (m) : ")
  y = float(input("Input feet (ft) : "))
  x = y / 3.28084;
  print("Converted Value from feet to meters " + str(x) + "m")

def kg_to_pounds():
  print("Convert kilograms (kg) to pounds (lbs) : ")
  y = float(input("Input kilograms (kg) : "))
  x = y * 2.20462;
  print("Converted Value from kg to pounds " + str(x) + "lbs")

def pounds_to_kg():
  print("Convert pounds (lbs) to kilograms (kg) : ")
  y = float(input("Input pounds (lbs) : "))
  x = y / 2.20462;
  print("Converted Value from pounds to kg " + str(x) + "kg")

def liters_to_gallons():
  print("Convert liters (L) to gallons (gal) : ")
  y = float(input("Input liters (L) : "))
  x = y * 0.264172;
  print("Converted Value from liters to gallons " + str(x) + "gal")

def gallons_to_liters():
  print("Convert gallons (gal) to liters (L) : ")
  y = float(input("Input gallons (gal) : "))
  x = y / 0.264172;
  print("Converted Value from gallons to liters " + str(x) + "L")

def main():
  while True:
    choice = input("\nEnter (1, 2, 3) or 'q' to quit : ")
    if choice == '1':
      print("\nLength Conversion: \n 1. Meters to Feet \n 2. Feet to Meters")
      choice = input("\nEnter (1, 2) or 'q' to quit : ")
      if choice == '1':
        meters_to_feet()
      elif choice == '2':
        feet_to_meters()
      elif choice == 'q':
        break
      else:
        print("Invalid choice")

    elif choice == '2':
      print("\nWeight Conversion: \n 1. Kilograms to Pounds \n 2. Pounds to Kilograms")
      choice = input("\nEnter (1, 2) or 'q' to quit : ")
      if choice == '1':
        kg_to_pounds()
      elif choice == '2':
        pounds_to_kg()
      elif choice == 'q':
        break
      else :
        print("Invalid choice")

    elif choice == '3':
      print("\nVolume Conversion: \n 1. Liters to Gallons \n 2. Gallons to Liters")
      choice = input("\nEnter (1, 2) or 'q' to quit : ")
      if choice == '1':
        liters_to_gallons()
      elif choice == '2':
        gallons_to_liters()
      elif choice == 'q':
        break
      else :
        print("Invalid choice")

    elif choice == 'q':
      print("Thank You for using the program.")
      break
    else:
      print("Invalid choice")


if __name__ == "__main__":
    main()



Python program that converts between different units of measurement.
Press  1  for length 
 Press 2 for weight 
 Press 3 for VOlume

Enter (1, 2, 3) or 'q' to quit : 1

Length Conversion: 
 1. Meters to Feet 
 2. Feet to Meters

Enter (1, 2) or 'q' to quit : 1
Convert meters (m) to feet (ft) : 
Input meters (m) : 5
Converted Value from meeter to feet 16.4042ft

Enter (1, 2, 3) or 'q' to quit : q
Thank You for using the program.


Task - 2:
Create a Python program that performs various mathematical operations on a list of numbers. • The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).


In [ ]:
print("Python program that performs various mathematical operations on a list of numbers.")
print("\n Press  1  for sum \n Press 2 for average \n Press 3 for maximum \n Press 4 for minimum")

def sum_numbers(numbers):
  total = 0
  for number in numbers:
    total += number
  return total

def average(numbers):
  total = sum_numbers(numbers)
  count = len(numbers)
  avg = total / count
  return avg

def maximum(numbers):
  max_value = numbers[0]
  for number in numbers:
    if number > max_value:
      max_value = number
  return max_value

def minimum(numbers):
  min_value = numbers[0]
  for number in numbers:
    if number < min_value:
      min_value = number
  return min_value

def main():
  while True:
    choice = input("\nEnter (1, 2, 3, 4) or 'q' to quit : ")

    if choice == '1':
      numbers = input("Enter a list of numbers separated by spaces: ").split()
      numbers = [float(number) for number in numbers]
      result = sum_numbers(numbers)
      print("The sum of the numbers is:", result)
    elif choice == '2':
      numbers = input("Enter a list of numbers separated by spaces: ").split()
      numbers = [float(number) for number in numbers]
      result = average(numbers)
      print("The average of the numbers is:", result)
    elif choice == '3':
      numbers = input("Enter a list of numbers separated by spaces: ").split()
      numbers = [float(number) for number in numbers]
      result = maximum(numbers)
      print("The maximum of the numbers is:", result)
    elif choice == '4':
      numbers = input("Enter a list of numbers separated by spaces: ").split()
      numbers = [float(number) for number in numbers]
      result = minimum(numbers)
      print("The minimum of the numbers is:", result)
    elif choice == 'q':
      print("Thank You for using the program.")
      break
    else:
      print("Invalid choice")

if __name__ == "__main__":
    main()


Python program that performs various mathematical operations on a list of numbers.

 Press  1  for sum 
 Press 2 for average 
 Press 3 for maximum 
 Press 4 for minimum
The sum of the numbers is: 15.0

Enter (1, 2, 3, 4) or 'q' to quit : q
Thank You for using the program.


**4.2 Exercise on List Manipulation:**

1. Extract Every Other Element:
Write a Python function that extracts every other element from a list, starting from the first element. • Requirements:
– Define a function extract every other(lst) that takes a list lst as input and returns a new list containing every other element from the original list.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].


In [ ]:
print("Extract Every Other Element")

numbers = input("Enter a list of numbers separated by spaces: ").split()
numbers = [float(number) for number in numbers]
result = list(numbers[::2])
print("The every other element is:", result)


Extract Every Other Element
Enter a list of numbers separated by spaces: 1 2 3 4 5 6 
The sum of the numbers is: [1.0, 3.0, 5.0]


2. Slice a Sublist:
Write a Python function that returns a sublist from a given list, starting from a specified index and ending at another specified index.
• Requirements:
– Define a function get sublist(lst, start, end) that takes a list lst, a starting index start, and an ending index end as input and returns the sublist from start to end (inclusive).
– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should be [3, 4, 5].


In [ ]:

print("Python function that returns a sublist from a given list, starting from a specified index and ending at another specified index.")
numbers = input("Enter a list of numbers separated by spaces: ").split()
numbers = [float(number) for number in numbers]
start = int(input("Enter the start index: "))
end = int(input("Enter the end index: "))


result = numbers[start:end]
print("Sublist : ", result)

Python function that returns a sublist from a given list, starting from a specified index and ending at another specified index.
Enter a list of numbers separated by spaces: 1 2 3 4 5 6 
Enter the start index: 0
Enter the end index: 3
Sublist :  [1.0, 2.0, 3.0]


3. Reverse a List Using Slicing:
Write a Python function that reverses a list using slicing.
• Requirements:
– Define a function reverse list(lst) that takes a list lst and returns a reversed list using slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].


In [ ]:
print(" Python function that reverses a list using slicing.  ")
numbers = input("Enter a list of numbers separated by spaces: ").split()
numbers = [float(number) for number in numbers]
original_list = numbers
reversed_list = original_list[::-1]
print("Original List : ", original_list)
print("Reversed List : ", reversed_list)

 Python function that reverses a list using slicing.  
Enter a list of numbers separated by spaces: 1 2 3 4 5 6
Original List :  [1.0, 2.0, 3.0, 4.0, 5.0, 6.0]
Reversed List :  [6.0, 5.0, 4.0, 3.0, 2.0, 1.0]


4. Remove the First and Last Elements:
Write a Python function that removes the first and last elements of a list and returns the resulting sublist.
• Requirements:
– Define a function remove first last(lst) that takes a list lst and returns a sublist without the first and last elements using slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].


In [ ]:
print(" Python function that removes the first and last elements of a list and returns the resulting sublist. ")
numbers = input("Enter a list of numbers separated by spaces: ").split()
numbers = [float(number) for number in numbers]
original_list = numbers
removed_list = original_list[1:-1]
print("Removed List : ", removed_list)

 Python function that removes the first and last elements of a list and returns the resulting sublist. 
Enter a list of numbers separated by spaces: 1 2 3 4 5 6
Removed List :  [2.0, 3.0, 4.0, 5.0]


5. Get the First n Elements:
Write a Python function that extracts the first n elements from a list.
• Requirements:
– Define a function get first n(lst, n) that takes a list lst and an integer n as input and returns the first n elements of the list using slicing.
– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].


In [ ]:
print(" Python function that extracts the first n elements from a list")
numbers = input("Enter a list of numbers separated by spaces: ").split()
numbers = [float(number) for number in numbers]
original_list = numbers
n = int(input("Enter the value of n element: "))

slice_element = original_list[:n]
print("first n elements of the list using slicing. ", slice_element)

 Python function that extracts the first n elements from a list
Enter a list of numbers separated by spaces: 1 2 3 4 5 6
Enter the value of n element: 2
first n elements of the list using slicing.  [1.0, 2.0]


6. Count Occurrences of an Element in a Nested List:
Write a Python function that counts how many times a specific element appears in a nested list. • Requirements:
– Define a function count occurrences(lst, elem) that counts the occurrences of elem in the nested list lst.
– Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should be 3.


In [ ]:
L = [[1, 2], [2, 3], [2, 4]]
sum(x.count(2) for x in L)


3

7. Flatten a List of Lists of Lists:
Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth. • Requirements:
– Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single flattened list.
– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be [1, 2, 3, 4, 5, 6, 7, 8].


In [ ]:
from more_itertools import collapse

list_of_lists_2 = [[1, 2], [[3, 4]], [5, [6, 7]]]
flattened_list_of_lists_2 = list(collapse(list_of_lists_2))
print(flattened_list_of_lists_2)

[1, 2, 3, 4, 5, 6, 7]


**4.3 Exercise on Nested List:**

1. Flatten a Nested List:
Write a Python function that takes a nested list and flattens it into a single list, where all the elements are in a single dimension.
• Requirements:
– Define a function flatten(lst) that takes a nested list lst and returns a flattened version of the list.
– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].


In [ ]:
from more_itertools import collapse

list_of_lists_2 = [[1, 2], [3, 4], [5]]
flattened_list_of_lists_2 = list(collapse(list_of_lists_2))
print(flattened_list_of_lists_2)

[1, 2, 3, 4, 5]


2. Accessing Nested List Elements:
Write a Python function that extracts a specific element from a nested list given its indices. • Requirements:
– Define a function access nested element(lst, indices) that takes a nested list lst and a list of indices indices, and returns the element at that position.
– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1, 2], the output should be 6.


In [ ]:
print("Write a Python function that extracts a specific element from a nested list given its indices.")
def access_nested_element(lst, indices):
    element = lst
    for index in indices:
        element = element[index]
    return element

nested_list = [
    [1, 2, [3, 4]],
    [5, [6, 7], 8],
    [9, 10]
]
indices = [0, 1]
result = access_nested_element(nested_list, indices)
print(result)

Write a Python function that extracts a specific element from a nested list given its indices.
2


3. Sum of All Elements in a Nested List:
Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth). • Requirements:
– Define a function sum nested(lst) that takes a nested list lst and returns the sum of all the elements.
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.


In [ ]:
from more_itertools import collapse

print("Python function that calculates the sum of all the numbers in a nested list (regardless of depth).")

def sum_nested(lst):
    return sum(collapse(lst))

nested_list = [[1, 2], [3, [4, 5]], 6]
result = sum_nested(nested_list)
print("Sum of the nested list : ",result)


Python function that calculates the sum of all the numbers in a nested list (regardless of depth).
Sum of the nested list :  21


4. Remove Specific Element from a Nested List:
Write a Python function that removes all occurrences of a specific element from a nested list. • Requirements:
– Define a function remove element(lst, elem) that removes elem from lst and returns the modified list.
– Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should be [[1], [3], [4, 5]].


In [ ]:
list = []
list_data = [[1, 2], [3, 2], [4, 5]]
list.append(list_data)

for sublist in list[0]:
    if 2 in sublist:
        sublist.remove(2)

print(list)


[[[1], [3], [4, 5]]]


. Find the Maximum Element in a Nested List:
 Write a Python function that finds the maximum element in a nested list (regardless of depth).
 • Requirements:– Define a function find
 element.
 max(lst) that takes a nested list lst and returns the maximum– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6

In [ ]:
def flatten(lst):
  flat_list = []
  for item in lst:
    if type(item) == list:
      flat_list.extend(flatten(item))
    else:
      flat_list.append(item)
  return flat_list

nested_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
flat_list = flatten(nested_list)
print(flat_list)
maximum_list = max(flat_list)
print("Maximum from the nested list : ", maximum_list)


[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
Maximum from the nested list :  [[5, 6], [7, 8]]


 6. Count Occurrences of an Element in a Nested List:
 Write a Python function that counts how many times a specific element appears in a nested list.
 • Requirements:– Define a function count
 occurrences(lst, elem) that counts the occurrences of elem in
 the nested list lst.– Example: Fortheinput lst = [[1, 2], [2, 3], [2, 4]]andelem = 2,theoutputshould
 be 3.

In [ ]:
from re import search
print("Write a Python function that counts how many times a specific element appears in a nested list.")

nested_list = [[1, 2], [2, 3], [2, 4]]
search_element = 2

count = sum([(search_element in sublist) for sublist in nested_list])
print(count)

Write a Python function that counts how many times a specific element appears in a nested list.
3


 7. Flatten a List of Lists of Lists:
 Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.
 • Requirements:– Define a function deep
 flatten(lst) that takes a deeply nested list lst and returns a single
 f
 lattened list.– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
 [1, 2, 3, 4, 5, 6, 7, 8]

In [ ]:
def flatten(lst):
  flat_list = []
  for item in lst:
    if type(item) == list:
      flat_list.extend(flatten(item))
    else:
      flat_list.append(item)
  return flat_list

nested_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
flat_list = flatten(nested_list)
print(" flattens a list of lists of lists into a single list : ", flat_list)

 flattens a list of lists of lists into a single list :  [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]


 8. Nested List Average:

 Write a Python function that calculates the average of all elements in a nested list.

 • Requirements:– Define a function average
 of all the elements.

 nested(lst) that takes a nested list lst and returns the average– Exam

In [ ]:
def flatten(lst):
  flat_list = []
  for item in lst:
    if type(item) == list:
      flat_list.extend(flatten(item))
    else:
      flat_list.append(item)
  return flat_list

def average(lst):
 return sum(lst) / len(lst)

nested_list = [[1, 2], [3, 4], [5, 6]]
flat_list = flatten(nested_list)
print("Average of the nested list : ", average(flat_list))

TypeError: unsupported operand type(s) for +: 'int' and 'list'

**NumPy**

10.1 Basic Vector and Matrix Operation with Numpy.
 Problem- 1: Array Creation:
 Complete the following Tasks:
 1. Initialize an empty array with size 2X2.


In [ ]:
import numpy as np
empty_array = np.empty((2, 2))
print(empty_array)
print(empty_array.shape)

[[2.71660236e-316 0.00000000e+000]
 [4.96947877e-091 5.85698235e+170]]
(2, 2)


 2. Initialize an all one array with size 4X2.


In [ ]:
import numpy as np
ones_array = np.ones((4, 2))
print(ones_array)
print(ones_array.shape)



[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
(4, 2)


 3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [ ]:
import numpy as np
ones_array = np.ones((4, 2))
# print(ones_array)
print(np.full(ones_array.shape, 5))


[[5 5]
 [5 5]
 [5 5]
 [5 5]]



 4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [ ]:
import numpy as np
ones_array = np.ones((4, 2))
print(np.zeros(ones_array.shape))

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


 5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [ ]:
import numpy as np
ones_array = np.ones((4, 2))
print(np.ones_like(ones_array.shape))

[1 1]




 6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np
new_list = [1,2,3,4]
print(type(np.array(new_list)))

<class 'numpy.ndarray'>


Problem- 2: Array Manipulation: Numerical Ranges and Array indexing:
 Complete the following tasks:

 1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.


In [ ]:
import numpy as np
array = np.arange(10, 49)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]



 2. Create a 3X3 matrix with values ranging from 0 to 8.
 {Hint:look for np.reshape()}

In [ ]:
import numpy as np
array = np.arange(9)
matrix = array.reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


 3. Create a 3X3 identity matrix.{Hint:np.eye()}


In [ ]:
import numpy as np
matrix = np.eye(3)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


 4. Create a random array of size 30 and find the mean of the array.

---


 {Hint:check for np.random.random() and array.mean() function}

In [ ]:
import numpy as np
array = np.random.random(30)
print(array.mean())

0.46038078007381866



 5. Create a 10X10 array with random values and find the minimum and maximum values.

In [ ]:
import numpy as np
array = np.random.random((10, 10))
print(array.min())
print(array.max())

0.0007700276922620874
0.9973669232121923


 6. Create a zero array of size 10 and replace 5th element with 1.


In [ ]:
import numpy as np
array = np.zeros(10)
array[4] = 1
print(array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


 7. Reverse an array arr = [1,2,0,0,4,0].


In [ ]:
import numpy as np
array = np.array( [1,2,0,0,4,0])
reverse = array[::-1]
print(reverse)

[0 4 0 0 2 1]


 8. Create a 2d array with 1 on border and 0 inside.


In [ ]:
import numpy as np
array = np.ones((5, 5))
array[1:-1, 1:-1] = 0  #RC
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]



.
 9. Create a 8X8 matrix and fill it with a checkerboard pattern.

 Problem- 3: Array Operations:
 For the following arrays:
 x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
 v = np.array([9,10]) and w = np.array([11,12]);
 Complete all the task using numpy:
 1. Add the two array.
 2. Subtract the two array.
 3. Multiply the array with any integers of your choice.
 4. Find the square of each element of the array.
 5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
 6. Concatenate x(and)y along row and Concatenate v(and)w along column.
 {Hint:try np.concatenate() or np.vstack() functions.
 7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
import numpy as np
checkerboard = np.ones((8, 8))
checkerboard[1::2, ::2] = 0
checkerboard[::2, 1::2] = 0
print(checkerboard)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [ ]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

add = x + y
print("Add : ", add)

subtract = x - y
print("Subtract : ", subtract)


multiply = x * y
print("Multiply : ", multiply)

dot_product = np.dot(v, w)
print("Dot Product : ", dot_product)

square_x = np.square(x)
square_y = np.square(y)
print("square_x : ", square_x)
print("square_y : ", square_y)




concatenate_along_row = np.concatenate((x, y), axis=0)
print("Concatenate along row : ", concatenate_along_row)

Add :  [[ 6  8]
 [10 13]]
Subtract :  [[-4 -4]
 [-4 -3]]
Multiply :  [[ 5 12]
 [21 40]]
Dot Product :  219
square_x :  [[ 1  4]
 [ 9 25]]
square_y :  [[25 36]
 [49 64]]
Concatenate along row :  [[1 2]
 [3 5]
 [5 6]
 [7 8]]


In [63]:
concatenate_along_row = np.concatenate((x, v.reshape(1, -1)), axis=0) # Reshape v to have 2 dimensions before concatenation.
print("Concatenate along row : ", concatenate_along_row)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [ ]:
print(x.shape)
print(v.shape)

(2, 2)
(2,)


In [ ]:
concatenate_along_row = np.concatenate((x, v.reshape(1, -1)), axis=0)
print("Concatenate along row : ", concatenate_along_row)

Concatenate along row :  [[ 1  2]
 [ 3  5]
 [ 9 10]]


 Problem- 4: Matrix Operations:
 • For the following arrays:
 A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
 Prove following with Numpy:
 1. Prove A.A−1 = I.
 2. Prove AB= BA.
 3. Prove (AB)T = BTAT.
 • Solve the following system of Linear equation using Inverse Methods.
 2x −3y+z =−1
 x −y+2z =−3
 3x +y−z =9
 {Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
 • Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func
tion of Numpy

In [ ]:
import numpy as np
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

A_inverse =  np.linalg.inv(A)
dot_prodeuct = np.dot(A, A_inverse)
print(dot_prodeuct)


[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [ ]:
AB = np.dot(A, B)
BA = np.dot(B, A)
print(AB)
print(BA)
if np.array_equal(AB, BA):
  print("AB = BA")
else:
  print("AB != BA")

[[23 13]
 [51 29]]
[[36 44]
 [13 16]]
AB != BA


In [ ]:
import numpy as np
# linalg.matrix_transpose(x, /)
AB_T = AB.T
BA_T = BA.T
print(AB_T)
print(BA_T)
if np.array_equal(AB_T, BA):
  print("AB_T = BA_T")
else:
  print("AB_T != BA_T")


[[23 51]
 [13 29]]
[[36 13]
 [44 16]]
AB_T != BA_T


In [ ]:
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([-1, -3, 9])
x = np.linalg.solve(A, B)
print(x)

[ 2.  1. -2.]


10.2 Experiment: How Fast is Numpy?
 In this exercise, you will compare the performance and implementation of operations using plain Python
 lists (arrays) and NumPy arrays. Follow the instructions:

1. Element-wise Addition:
 • Using Python Lists, perform element-wise addition of two lists of size 1,000,000. Measure
 and Print the time taken for this operation.
 • Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
 this operation.

In [ ]:
import numpy as np
import time
import random

import sys
# from pympler.asizeof import asizeof

n = 1000000
a_list = random.sample(range(1, 1000001), n)
b_list = random.sample(range(1, 1000001), n)

start_time = time.time()
# Use a different variable name, like 'list_sum' to avoid overwriting built-in 'list'
list_sum = [x + y for x, y in zip(a_list, b_list)]
end_time = time.time()
list_time = end_time - start_time

print("Time taken for list addition:", list_time)

print("Meomory used : ", sys.getsizeof(list_sum))

Time taken for list addition: 0.36441922187805176
Meomory used :  8448728


In [ ]:
import numpy as np
import time
import random

a_list = [random.randint(0, 1000000) for _ in range(1000000)]
b_list = [random.randint(0, 1000000) for _ in range(1000000)]


start_time = time.time()
list_sum = [a + b for a, b in zip(a_list, b_list)]
end_time = time.time()
list_time = end_time - start_time

print("Time taken for list addition:", list_time)

print("Meomory used : ", sys.getsizeof(list_sum))


Time taken for list addition: 0.0764617919921875
Meomory used :  8448728


In [ ]:
a_numpy = np.array(a_list)
b_numpy = np.array(b_list)

start_time = time.time()
numpy_sum = np.add(a_numpy, b_numpy)
end_time = time.time()
numpy_time = end_time - start_time

print("Time taken for NumPy array addition:", numpy_time)

print("Meomory used : ", sys.getsizeof(numpy_sum))


Time taken for NumPy array addition: 0.008145332336425781
Meomory used :  8000112


 2. Element-wise Multiplication


 • Using Python Lists, perform element-wise multiplication of two lists of size 1,000,000.

 Measure and Print the time taken for this operation.

 • Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
 this operation.

In [ ]:
list_sum = [a * b for a, b in zip(a_list, b_list)]
start_time = time.time()
print("Time taken for list multiplication:", list_time)
end_time = time.time()
list_time = end_time - start_time
print("Meomory used : ", sys.getsizeof(list_sum))

Time taken for list multiplication: 0.0764617919921875
Meomory used :  8448728


In [ ]:
start_time = time.time()
numpy_multi = np.multiply(a_numpy, b_numpy)
end_time = time.time()
numpy_time = end_time - start_time

print("Time taken for NumPy array addition:", numpy_time)

print("Meomory used : ", sys.getsizeof(numpy_multi))

Time taken for NumPy array addition: 0.0034155845642089844
Meomory used :  8000112


 3. Dot Product
 • Using Python Lists, compute the dot product of two lists of size 1,000,000. Measure and
 Print the time taken for this operation.
 • Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
 this operation.

In [ ]:
start_time = time.time()
dot_product_list = sum(a * b for a, b in zip(a_list, b_list))

end_time = time.time()
list_time = end_time - start_time

print("Time taken for list addition:", list_time)

print("Memory used by lists:", sys.getsizeof(a_list) + sys.getsizeof(b_list), "bytes")


Time taken for list addition: 0.08862185478210449
Memory used by lists: 16897456 bytes


In [ ]:
start_time = time.time()
numpy_dot = np.dot(a_numpy, b_numpy)
end_time = time.time()
numpy_time = end_time - start_time

print("Time taken for NumPy array addition:", numpy_dot)

print("Memory used by NumPy arrays:", a_numpy.nbytes + b_numpy.nbytes, "bytes")


Time taken for NumPy array addition: 250209216752992263
Memory used by NumPy arrays: 16000000 bytes


4. Matrix Multiplication

 • Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Mea

sure and print the time taken for this operation.

 • Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.

 Measure and print the time taken for this operation

In [62]:
import time
import numpy as np

# Matrix size
N = 1000

# Generate random matrices
A_list = [[i * j for j in range(N)] for i in range(N)]
B_list = [[j * i for j in range(N)] for i in range(N)]

A_numpy = np.array(A_list)
B_numpy = np.array(B_list)

# Matrix Multiplication using Python lists
def matrix_mult_list(A, B):
    result = [[0] * N for _ in range(N)]
    for i in range(N):
        for j in range(N):
            result[i][j] = sum(A[i][k] * B[k][j] for k in range(N))
    return result

# Measure time for Python lists
start_time = time.time()
result_list = matrix_mult_list(A_list, B_list)
end_time = time.time()
list_time = end_time - start_time

print(f"Time taken using Python lists: {list_time:.6f} sec")

# Measure time for NumPy arrays
start_time = time.time()
result_numpy = np.dot(A_numpy, B_numpy)  # OR: A_numpy @ B_numpy
end_time = time.time()
numpy_time = end_time - start_time

print(f"Time taken using NumPy: {numpy_time:.6f} sec")


Time taken using Python lists: 253.558943 sec
Time taken using NumPy: 2.103546 sec
